export * from "./About/About"
export * from "./Skills/Skills"
export * from "./Projects/Projects"

export * from "./Header/Header"
export * from "./Navbar/Navbar"
export * from "./Footer/Footer"

export * from "./LanguageSwitcher/LanguageSwitcher"
export * from "./DownloadResume/DownloadResume"
export * from "./Repos/Repos"
export * from "./Button/Button"
export * from "./Title/Title"
export * from "./Card/Card"
export * from "./Social/Social"
